apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-db-backup
spec:
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  refreshInterval: "12h"
  target:
    name: rustfs-db-backup
    deletionPolicy: "Delete"
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kan,n8n"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  dataFrom:
    - extract:
        key: '/homelab/rustfs/db-backup'
