apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'external-secrets'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
    - ServerSideApply=true
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.19.1
    helm:
      values: |-
        nameOverride: "external-secrets"
        fullnameOverride: "external-secrets"
        resources:
          limits:
            cpu: 80m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 80Mi
        webhook:
          create: false
        certController:
          create: false
