apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kan-db
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'kan'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cluster
    targetRevision: 0.6.0
    helm:
      values: |-
        nameOverride: kan
        fullnameOverride: kan
        version:
          postgresql: "18"
        mode: standalone # change to "recovery" when running DB restore
        cluster:
          instances: 1
          storage:
            size: 2Gi
          resources:
            limits:
              memory: 850Mi
              cpu: 850m
            requests:
              memory: 700Mi
              cpu: 700m
          initdb:
            database: kanbn
        backups:
          enabled: true
          endpointURL: "http://rustfs-cli.rustfs.svc.cluster.local:9000"
          provider: s3
          s3:
            region: "eu-central-1"
            bucket: "db-backup"
            path: "/kanbn"
          secret:
            create: false
            name: "rustfs-db-backup"
          scheduledBackups:
            - name: daily-backup
              schedule: "0 0 21 * * *"
              backupOwnerReference: self
              method: barmanObjectStore
        recovery:
          provider: s3
          method: object_store
          clusterName: "kan"
          database: kanbn
          s3:
            region: "eu-central-1"
            bucket: "db-backup"
            path: "/kanbn"
