apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kan-db
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'kan'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cluster
    targetRevision: 0.5.0
    helm:
      values: |-
        nameOverride: kan
        fullnameOverride: kan
        version:
          postgresql: "18"
        cluster:
          instances: 1
          storage:
            size: 2Gi
          resources:
            limits:
              memory: 850Mi
              cpu: 850m
            requests:
              memory: 700Mi
              cpu: 700m
          initdb:
            database: kanbn
