apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelet-serving-cert-approver
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'kubelet-serving-cert-approver'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    path: 'argocd/kustomize/kubelet-serving-cert-approver'
    repoURL: https://github.com/lewandowskim1988/home-lab.git
    targetRevision: HEAD
