apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: metallb
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/warn: privileged
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.15.3
    helm:
      values: |-
        nameOverride: "metallb"
        fullnameOverride: "metallb"
        controller:
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 120m
              memory: 350Mi
        speaker:
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 120m
              memory: 350Mi