apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'n8n'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    repoURL: '8gears.container-registry.com/library'
    chart: n8n
    path: n8n
    targetRevision: 2.0.1
    helm:
      values: |-
        nameOverride: n8n
        fullnameOverride: n8n
        image:
          tag: "2.6.2"
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          className: "nginx"
          hosts:
            - host: n8n.lewandowskim.com
              paths:
                - path: "/"
                  pathType: Prefix
          tls:
            - hosts:
                - n8n.lewandowskim.com
              secretName: tls-wildcard-lewandowskim-com
        main:
          persistence:
            enabled: true
            type: dynamic
            size: 5Gi
          extraEnv:
            N8N_EDITOR_BASE_URL:
              value: "https://n8n.lewandowskim.com"
            WEBHOOK_URL:
              value: "https://n8n.lewandowskim.com"
            N8N_PAYLOAD_SIZE_MAX:
              value: "268435456"
          # extraVolumes:
          #   - name: share
          #     persistentVolumeClaim:
          #       claimName: filebrowser-rootdir
          # extraVolumeMounts:
          #   - name: share
          #     mountPath: /n8n/share
