apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'n8n'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: n8n
    path: community-charts
    targetRevision: 1.16.35
    helm:
      values: |-
        nameOverride: n8n
        fullnameOverride: n8n
        # db:
        #   type: postgresdb
        main:
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "1"
              memory: 1.5Gi
          persistence:
            enabled: true
            size: 2Gi
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          hosts:
            - host: n8n.lewandowskim.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: tls-wildcard-lewandowskim-com
              hosts:
                - n8n.lewandowskim.com
        # externalPostgresql:
        #   host: ""
        #   username: "postgres"
        #   password: ""
        #   port: 5432
        #   database: n8n
        #   # -- The name of an existing secret with PostgreSQL (must contain key `postgres-password`) and credentials.
        #   # When it's set, the `externalPostgresql.password` parameter is ignored
        #   existingSecret: ""
