apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'ollama'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    repoURL: https://otwld.github.io/ollama-helm/
    chart: ollama
    targetRevision: 1.26.0
    helm:
      values: |-
        nameOverride: ollama
        fullnameOverride: ollama
        ollama:
          gpu:
            enabled: true
            type: "amd"
          models:
            pull:
              - devstral:24b
              - mistral-small3.2:24b
              - bge-m3:567m
              - llama3.2:3b
              - qwen2.5vl:7b-q8_0
            run: []
            create:
              - name: bge-m3-ctx32768
                template: |
                  FROM bge-m3:567m
                  PARAMETER num_ctx 32768
        resources:
          requests:
            memory: 3Gi
            cpu: 2
        persistentVolume:
          enabled: true
          size: 100Gi
          storageClass: "openebs-lvmpv"
        extraEnv:
          - name: OLLAMA_FLASH_ATTENTION
            value: "1"
          - name: OLLAMA_CONTEXT_LENGTH
            value: "8192"
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          hosts:
            - host: ollama.lewandowskim.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: tls-wildcard-lewandowskim-com
              hosts:
                - ollama.lewandowskim.com
