apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'ollama'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    repoURL: https://otwld.github.io/ollama-helm/
    chart: ollama
    targetRevision: 1.28.0
    helm:
      values: |-
        nameOverride: ollama
        fullnameOverride: ollama
        image:
          tag: "0.11.11-rocm"
        ollama:
          gpu:
            enabled: true
            type: "amd"
          models:
            pull:
              - mistral-small3.2:24b
              - llama3.2:3b
              - qwen3-coder:30b
              - qwen3:30b
              - dengcao/Qwen3-Embedding-4B:Q4_K_M
            run: []
            create:
              - name: Qwen3-Embedding-4B
                template: |
                  FROM dengcao/Qwen3-Embedding-4B:Q4_K_M
        resources:
          requests:
            memory: 4Gi
            cpu: 2
        persistentVolume:
          enabled: true
          size: 200Gi
          storageClass: "openebs-lvmpv"
        extraEnv:
          - name: OLLAMA_FLASH_ATTENTION
            value: "1"
          - name: OLLAMA_CONTEXT_LENGTH
            value: "8192"
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          hosts:
            - host: ollama.lewandowskim.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: tls-wildcard-lewandowskim-com
              hosts:
                - ollama.lewandowskim.com
