# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: pgvector
#   namespace: argocd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   destination:
#     namespace: 'pgvector'
#     server: 'https://kubernetes.default.svc'
#   project: apps
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - CreateNamespace=true
#     - ApplyOutOfSyncOnly=true
#     - PruneLast=true
#   source:
#     repoURL: 'registry-1.docker.io/bitnamicharts'
#     chart: postgresql
#     path: postgresql
#     targetRevision: 16.4.16
#     helm:
#       values: |-
#         nameOverride: postgresql
#         fullnameOverride: postgresql
#         global:
#           defaultStorageClass: "openebs-lvmpv"
#           security:
#             allowInsecureImages: "true"
#         postgresqlSharedPreloadLibraries: "pgaudit,vector"
#         image:
#           registry: docker.io
#           repository: lewandowskim/postgres-vector
#           tag: 17.4.0
#         primary:
#           extendedConfiguration: |-
#             max_connections = 300
#             shared_buffers = 256MB
#           resources:
#             limits:
#               memory: 850Mi
#               cpu: 850m
#             requests:
#               memory: 700Mi
#               cpu: 700m
#           persistence:
#             size: 10Gi
#         auth:
#           existingSecret: "n8n-postgres-password"
#           secretKeys:
#             adminPasswordKey: postgresPassword
#             replicationPasswordKey: replicationPassword
#         extraDeploy:
#           - apiVersion: external-secrets.io/v1
#             kind: ExternalSecret
#             metadata:
#               name: n8n-postgres-password
#             spec:
#               secretStoreRef:
#                 name: aws-parameter-store
#                 kind: ClusterSecretStore
#               refreshInterval: "1h"
#               target:
#                 name: n8n-postgres-password
#                 deletionPolicy: "Delete"
#               dataFrom:
#                 - extract:
#                     key: "/homelab/n8n-postgres-password"

