apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'media'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    path: 'argocd/helm/qbittorrent'
    repoURL: https://github.com/lewandowskim1988/home-lab.git
    targetRevision: HEAD
    helm:
      values: |-
        nameOverride: "qbittorrent"
        fullnameOverride: "qbittorrent"
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          hosts:
            - host: qbittorrent.lewandowskim.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - hosts:
                - qbittorrent.lewandowskim.com
              secretName: tls-wildcard-lewandowskim-com
        envFrom:
          - secretRef:
              name: qbittorrent-api-key
        exportarr:
          enabled: true
          image:
            repository: "ghcr.io/onedr0p/exportarr"
            tag: "v2.3.0"
