apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'media'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    path: 'argocd/helm/radarr'
    repoURL: https://github.com/lewandowskim1988/home-lab.git
    targetRevision: HEAD
    helm:
      values: |-
        nameOverride: "radarr"
        fullnameOverride: "radarr"
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          hosts:
            - host: radarr.lewandowskim.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - hosts:
                - radarr.lewandowskim.com
              secretName: tls-wildcard-lewandowskim-com
        envFrom:
          - secretRef:
              name: radarr-api-key
        mediaVolume:
          enabled: true
          name: "qbittorrent-media"
        exportarr:
          enabled: true
          image:
            repository: "ghcr.io/onedr0p/exportarr"
            tag: "v2.3.0"
          envFrom:
            - secretRef:
                name: radarr-api-key
        extraObjects:
          - apiVersion: secretgen.k14s.io/v1alpha1
            kind: Password
            metadata:
              name: radarr-api-key
            spec:
              length: 30
              secretTemplate:
                type: Opaque
                stringData:
                  RADARR__AUTH__APIKEY: $(value)
                  APIKEY: $(value)
