apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secretgen-controller
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'secretgen-controller'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    path: 'argocd/kustomize/secretgen-controller'
    repoURL: https://github.com/lewandowskim1988/home-lab.git
    targetRevision: HEAD
