# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: sftpgo-server
#   namespace: argocd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   destination:
#     namespace: 'media'
#     server: 'https://kubernetes.default.svc'
#   project: apps
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - CreateNamespace=true
#     - ApplyOutOfSyncOnly=true
#     - PruneLast=true
#   source:
#     repoURL: ghcr.io/sftpgo/helm-charts
#     chart: sftpgo
#     targetRevision: 0.40.0
#     helm:
#       values: |-
#         nameOverride: "sftpgo"
#         fullnameOverride: "sftpgo"
#         # sftpd:
#         #   port: 2222
#         # service:
#         #   type: LoadBalancer
#         ui:
#           ingress:
#             enabled: true
#             className: "nginx"
#             annotations:
#               nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#               nginx.ingress.kubernetes.io/ssl-redirect: "true"
#             hosts:
#               - host: sftp.lewandowskim.com
#                 paths:
#                   - path: "/"
#                     pathType: ImplementationSpecific
#             tls:
#               - hosts:
#                   - sftp.lewandowskim.com
#                 secretName: tls-wildcard-lewandowskim-com
#         volumes:
#           - name: custom-config # config is already taken
#             configMap:
#               name: custom-sftpgo-config
#         volumeMounts:
#           - name: custom-config # config is already taken
#             mountPath: /var/lib/sftpgo/.config/sftpgo
#         resources:
#           limits:
#             cpu: 1
#             memory: 1Gi
#           requests:
#             cpu: 800m
#             memory: 800Mi
#         persistence:
#           enabled: true
#           pvc:
#             resources:
#               requests:
#                 storage: 1Gi
#             storageClassName: "openebs-lvmpv"
