apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sftp-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'media'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    repoURL: https://sj14.github.io/helm-charts
    chart: sftp-server
    targetRevision: 0.8.0
    helm:
      values: |-
        nameOverride: "sftp-server"
        fullnameOverride: "sftp-server"
        persistentVolume:
          enabled: true
          size: 10Gi