apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: external-dns
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  refreshInterval: "12h"
  target:
    name: cloudflare-api-token-secret
    deletionPolicy: "Delete"
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "cert-manager"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  data:
    - secretKey: api-token
      remoteRef:
        key: "/homelab/cloudflare-api-token-secret"
