apiVersion: v1
kind: Service
metadata:
  name: "{{ include "qbittorrent.fullname" . }}-metrics"
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9707
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "qbittorrent.selectorLabels" . | nindent 4 }}
