{
 "title": "AMD GPU usage",
 "description": "Overview of the system",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "g_gpu_uuids", "query": { "query": "label_values(GPU_UUID)" } },
   { "name": "g_job_ids", "query": { "query": "label_values(job_id)" } },
   { "name": "g_mi300_model", "label": "MI300 Model", "query": "102-G30211-00" }
  ]
 },
 "panels": [
  {
   "title": "GPUs",
   "type": "stat",
   "description": "Number of GPUs in the node",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gpu_nodes_total)", "legendFormat": "GPUs" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gpu_used_vram)", "legendFormat": "__auto" },
    { "expr": "sum(gpu_total_vram)", "legendFormat": "__auto" },
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "PCIe Max Speed",
   "type": "stat",
   "description": "Current maximum PCIe speed",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"count\", pcie_max_speed)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCIe Counts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pcie_recovery_count)", "legendFormat": "Recovery" },
    { "expr": "sum(pcie_replay_count)", "legendFormat": "Replay" },
    {
     "expr": "sum(pcie_replay_rollover_count)",
     "legendFormat": "Replay Rollover"
    },
    { "expr": "sum(pcie_nack_received_count)", "legendFormat": "NACK Received" },
    { "expr": "sum(pcie_nack_sent_count)", "legendFormat": "NACK Sent" }
   ]
  },
  {
   "title": "Top 5 GPU Usage",
   "type": "stat",
   "description": "Top 5 current GPU GFX Activity, labeled with hostname, GPU ID, and job ID.",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk by() (5, gpu_gfx_activity)",
     "legendFormat": "{{ `{{hostname}}` }} | {{ `{{gpu_id}}` }} | {{ `{{job_id}}` }}"
    }
   ]
  },
  {
   "title": "Top 5 Used VRAM",
   "type": "stat",
   "description": "Top 5 GPUs with highest VRAM used, labeled with hostname and GPU ID.",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, gpu_used_vram)",
     "legendFormat": "{{ `{{hostname}}` }} | {{ `{{gpu_id}}` }}"
    }
   ]
  },
  {
   "title": "Current Total PCIe Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pcie_bandwidth)", "legendFormat": "Total current PCIe bandwidth" }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "description": "Number of jobs",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group by(job_id) (gpu_gfx_activity{job_id!=\"\"}))",
     "legendFormat": "Jobs"
    },
    {
     "expr": "sum(group by(pod) (gpu_gfx_activity{pod!=\"\"}))",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Energy Consumed",
   "type": "stat",
   "description": "Total accumulated energy consumed",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gpu_energy_consumed)",
     "legendFormat": "Accumulated Energy Consumed (nJ)"
    },
    { "expression": "$A / 1000000", "type": "math" }
   ]
  },
  {
   "title": "Total PCIe Bandwidth",
   "type": "timeseries",
   "description": "Total PCIe Bandwidth over time",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    { "expr": "sum(pcie_bandwidth)", "legendFormat": "Total PCIe Bandwidth" }
   ]
  },
  {
   "title": "Total Power Usage",
   "type": "timeseries",
   "description": "Total power usage, in Watts",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "sum(gpu_power_usage)", "legendFormat": "Power Usage (W)" }
   ]
  },
  {
   "title": "Average GPU Power",
   "type": "timeseries",
   "description": "Average GPU package power, in Watts",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "avg(gpu_package_power)", "legendFormat": "GPU Power" }
   ]
  },
  {
   "title": "Average GPU Usage",
   "type": "timeseries",
   "description": "Average of current GPU GFX activity",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "avg(gpu_gfx_activity)", "legendFormat": "GPU Usage" }
   ]
  },
  {
   "title": "Used VRAM",
   "type": "timeseries",
   "description": "Used VRAM over time",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Average Sensor Temperatures",
   "type": "timeseries",
   "description": "Average current temperatures, in Celsius, from:\n- HBM (4 sensors)\n- Edge\n- Junction/hotspot",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "avg(gpu_hbm_temperature)", "legendFormat": "HBM Temperature" },
    { "expr": "avg(gpu_edge_temperature)", "legendFormat": "Edge Temperature" },
    { "expr": "avg(gpu_junction_temperature)", "legendFormat": "Junction Temperature" }
   ]
  },
  {
   "title": "Average GPU Temperature",
   "type": "timeseries",
   "description": "Current temperature, in Celsius",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(gpu_edge_temperature{card_model!=\"$g_mi300_model\"})",
     "legendFormat": "Edge Temperature"
    },
    {
     "expr": "avg(gpu_junction_temperature{card_model=\"$g_mi300_model\"})",
     "legendFormat": "Junction Temperature"
    }
   ]
  },
  {
   "title": "Average Memory Temperature",
   "type": "timeseries",
   "description": "Current memory temperature, in Celsius",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "avg(gpu_memory_temperature)", "legendFormat": "Memory Temperature" }
   ]
  },
  {
   "title": "All GPUs",
   "type": "table",
   "description": "List of all GPUs. Click on the row to go to that GPU's dashboard (opens new tab).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    { "expr": "gpu_gfx_activity", "legendFormat": "__auto" }
   ]
  }
 ]
}