apiVersion: v1
kind: Service
metadata:
  name: "{{ include "radarr.fullname" . }}-metrics"
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9707
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "radarr.selectorLabels" . | nindent 4 }}
